apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  services.yaml: |
    - Homelab:
        - Grafana:
            href: http://Change Me
            description: Monitoring and Analytics
            icon: grafana
        - Pi-hole:
            href: http://Change Me/admin/
            description: Network-wide Ad Blocking
            icon: pi-hole
            # widget:
            #   type: pihole
            #   url: http://Change Me/api
            #   version: 6
            #   key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"
        - ArgoCD:
            href: http://Change Me
            description: GitOps Continuous Delivery
            icon: argo-cd
        - pgAdmin:
            href: http://Change Me
            description: PostgreSQL Administration
            icon: pgadmin
    - Creating:
        - Excalidraw:
            href: http://Change Me
            description: Virtual Whiteboard
            icon: excalidraw
        - n8n:
            href: http://Change Me
            description: Workflow Automation
            icon: n8n
        - Code Server:
            href: http://Change Me
            description: VS Code in the browser
            icon: code-server

  widgets.yaml: |
    - search:
        provider: google
        target: _blank
    - datetime:
        text_size: xl
        locale: en
        dateStyle: long
        timeStyle: short
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
        nodes:
          show: true
          cpu: true
          memory: true
    - resources:
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true

  bookmarks.yaml: ""
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: Change Me
            - name: HOMEPAGE_VAR_PIHOLE_KEY
              value: "Change Me"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/custom.js
              name: homepage-config
              subPath: custom.js
      volumes:
        - name: homepage-config
          configMap:
            name: homepage-config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
  namespace: homepage
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: "Change Me"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homepage
            port:
              number: 80
