apiVersion: v1
kind: Secret
metadata:
  name: in-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    enable_code-server: "true"
    enable_excalidraw: "true"
    enable_homepage: "true"
    enable_n8n: "true"
    enable_pgadmin: "true"
    enable_pihole: "true"
    enable_kube-prometheus-stack: "true"
type: Opaque
stringData:
  name: in-cluster
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }
