apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw-deployment
  namespace: excalidraw
  labels:
    app: excalidraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      containers:
      - name: excalidraw
        image: excalidraw/excalidraw:latest
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-web
  namespace: excalidraw
spec:
  type: ClusterIP
  selector:
    app: excalidraw
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excalidraw-ingress
  namespace: excalidraw
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: "excalidraw.home.devopsinthe.cloud"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: excalidraw-web
            port:
              name: http
